= Text

== &sect;Constrained

.Bold
Here's a *sample* AsciiDoc document:

.italic
Here's a _sample_ AsciiDoc document:

.highlight
Here's a #sample# AsciiDoc document:

.monospace
Here's a `sample` AsciiDoc document:

.superscript
Here's a ^sample^ AsciiDoc document:

.subscript
Here's a ~sample~ AsciiDoc document:

.quotes-single;;
Here's a `'sample'` AsciiDoc document:

.quotes-double
Here's a `"sample"` AsciiDoc document:

== Unconstrained

.Bold
*H*ere's a sample AsciiDoc document:

**H**ere's a sample AsciiDoc document:

.italic
Here's a #s#ample AsciiDoc document:

Here's a ##s##ample AsciiDoc document:

.Monospace
Here's a `s`ample AsciiDoc document:

Here's a ``s``ample AsciiDoc document:

== Mixing

.order: Monospace > other > italic
Here's a `*_sample_*` AsciiDoc document:

== Literal Monospace

You can reference the value of a document attribute using the syntax `+{name}+`, where `name` is the attribute name.

`pass:[++]` is the increment operator in C.

== Built-in Role for Text

Here's a [.big]#sample# AsciiDoc document:

Here's a [.small]#sample# AsciiDoc document:

Here's a [.underline]#sample# AsciiDoc document:

Here's a [.overline]#sample# AsciiDoc document:

Here's a [.line-through]#sample# AsciiDoc document:

// Here's a [.nobreak]#sample AsciiDoc# document:
//
// Here's a [.pre-wrap]#sample AsciiDoc# document:
//
// Here's a [.nowrap]#sample AsciiDoc# document:
//

== Quote

Olaf's desk was a mess.

Olaf\'s desk was a mess.

``npm```'s job is to manage the dependencies for your application.

A ``std::vector```'s size is the number of items it contains.

== Quote Plus

"end points"

"`end points`"

"``end points``"

"```end points```"

\"``end points``" or "[.code]``end points``"

== Prevent Substitutions

In /items/\{id}, the id attribute isn't replaced.
The curly braces around it are preserved.

*Stars* isn't displayed as bold text.
The asterisks around it are preserved.

\&sect; appears as an entity reference.
It's not converted into the section symbol (&sect;).

\=> The backslash prevents the equals sign followed by a greater than sign from combining to form a double arrow character (=>).

\[[Word]] is not interpreted as an anchor.
The double brackets around it are preserved.

[\[[Word]]] is not interpreted as a bibliography anchor.
The triple brackets around it are preserved.

The URL \https://example.org isn't converted into an active link.

The text \\__func__ will appear with two underscores in front of it and after it.
It won't be italicized.